"""
Configuration for different tabs in the SteamLauncherGUI application.
"""

# Tab configurations for various enhancement tools
TAB_CONFIGS = {
    "Wine": {
        "enable_label": "Enable Wine",
        "enable_tooltip": "Enable Wine environment settings",
        "env_prefix": "",
        "toggles": [
            ("WINEESYNC", "Enable explicit synchronization for Wine"),
            ("WINEFSYNC", "Enable frame synchronization for Wine"),
            ("WINELOADERDEBUG", "Enable Wine loader debugging"),
            ("WINELOADERNOEXEC", "Disable Wine loader execution"),
        ],
        "inputs": [
            ("WINEPREFIX", "Path to Wine prefix", "e.g., /path/to/prefix"),
            ("WINEARCH", "Set Wine architecture", "e.g., win32"),
            ("WINEDLLOVERRIDES", "Override specific DLLs", "e.g., dxgi=n,b"),
            ("WINEDEBUG", "Set Wine debug level", "e.g., +relay"),
            ("WINELOGFILE", "Path to Wine log file", "e.g., /path/to/logfile"),
            ("WINESERVER", "Path to wineserver binary", "e.g., /path/to/wineserver"),
            ("WINELOADER", "Path to Wine loader", "e.g., /path/to/wine"),
            ("WINEDLLPATH", "Path to DLL directory", "e.g., /path/to/dlls"),
            ("WINEBIN", "Path to Wine binary", "e.g., /path/to/wine"),
        ],
    },
    "MangoHud": {
        "enable_label": "Enable MangoHud",
        "enable_tooltip": "Enable MangoHud overlay",
        "env_prefix": "",
        "command_prefix": "mangohud",
        "toggles": [
            ("MANGOHUD", "Enable MangoHud overlay"),
            ("MANGOHUD_DLSYM", "Use dlsym to load MangoHud"),
            ("MANGOHUD_GAMEPAD", "Enable gamepad support in MangoHud"),
            ("MANGOHUD_LOG", "Enable logging for MangoHud"),
            ("MANGOHUD_HWINFO", "Display hardware information in MangoHud"),
            ("MANGOHUD_SHORT", "Display a shorter overlay in MangoHud"),
            ("MANGOHUD_FPS", "Display FPS in MangoHud"),
            ("MANGOHUD_GPU", "Display GPU usage in MangoHud"),
            ("MANGOHUD_CPU", "Display CPU usage in MangoHud"),
            ("MANGOHUD_VK", "Display Vulkan-specific information in MangoHud"),
            ("MANGOHUD_GL", "Display OpenGL-specific information in MangoHud"),
            ("MANGOHUD_MEMORY", "Display memory usage in MangoHud"),
            ("MANGOHUD_TEMP", "Display GPU temperature in MangoHud"),
            ("MANGOHUD_POWER", "Display GPU power usage in MangoHud"),
        ],
        "inputs": [
            ("MANGOHUD_CONFIG", "Path to custom MangoHud config file", "e.g., /path/to/config"),
            ("MANGOHUD_FPSAVERAGE", "Average FPS over frames", "e.g., 100"),
            ("MANGOHUD_FPS_LIMIT", "Set frame rate limit", "e.g., 60"),
            ("MANGOHUD_FPS_THRESHOLD", "Set FPS alert threshold", "e.g., 30"),
            ("MANGOHUD_COLOR", "Set overlay color", "e.g., #FF0000"),
            ("MANGOHUD_XOFFSET", "Adjust X offset of overlay", "e.g., 10"),
            ("MANGOHUD_YOFFSET", "Adjust Y offset of overlay", "e.g., 10"),
        ],
        "dropdowns": {
            "MANGOHUD_ALIGN": {
                "label": "ALIGN:",
                "options": ["bottom", "top", "left", "right"],
                "tooltip": "Align the MangoHud overlay",
                "default": "top",
            }
        },
        "software_requirement": "mangohud",
    },
    "vkBasalt": {
        "enable_label": "Enable vkBasalt",
        "enable_tooltip": "Enable vkBasalt effects",
        "env_prefix": "",
        "toggles": [
            ("VK_BASALT_DISABLE", "Disable vkBasalt effects"),
            ("VK_BASALT_SHARPEN", "Enable sharpening effect"),
            ("VK_BASALT_FXAA", "Enable fast approximate anti-aliasing"),
            ("VK_BASALT_SMAA", "Enable subpixel morphological anti-aliasing"),
            ("VK_BASALT_LUT", "Enable lookup table (LUT) color grading"),
            ("VK_BASALT_TONEMAP", "Enable tonemapping"),
            ("VK_BASALT_HDR", "Enable HDR support"),
            ("VK_BASALT_DITHER", "Enable dithering"),
            ("VK_BASALT_LUMINANCE", "Enable luminance adjustment"),
            ("VK_BASALT_COLOR", "Enable color adjustment"),
            ("VK_BASALT_BLOOM", "Enable bloom effect"),
            ("VK_BASALT_SSAO", "Enable screen-space ambient occlusion"),
            ("VK_BASALT_VIGNETTE", "Enable vignette effect"),
            ("VK_BASALT_CHROMATIC_ABER", "Enable chromatic aberration"),
            ("VK_BASALT_MOTION_BLUR", "Enable motion blur"),
        ],
        "inputs": [
            ("VK_BASALT_CONFIG", "Path to custom vkBasalt config file", "e.g., /path/to/config"),
            ("VK_BASALT_SHADERS", "Path to custom shaders", "e.g., /path/to/shaders"),
            ("AMD_VULKAN_ICD", "Force specific AMD Vulkan ICD", "e.g., RADV"),
            ("RADV_PERFTEST", "Set RADV performance tests", "e.g., rt,gpl"),
            ("RADV_DEBUG", "Set RADV debug options", "e.g., shader"),
            ("VKD3D_CONFIG", "Set VKD3D config options", "e.g., dxr12"),
        ],
        "sliders": [
            ("VK_BASALT_SHARPEN_STRENGTH", "Sharpening strength", 0.0, 1.0),
            ("VK_BASALT_FXAA_STRENGTH", "FXAA strength", 0.0, 1.0),
            ("VK_BASALT_SMAA_STRENGTH", "SMAA strength", 0.0, 1.0),
            ("VK_BASALT_LUT_STRENGTH", "LUT strength", 0.0, 1.0),
            ("VK_BASALT_TONEMAP_STRENGTH", "Tonemapping strength", 0.0, 1.0),
            ("VK_BASALT_HDR_STRENGTH", "HDR strength", 0.0, 1.0),
            ("VK_BASALT_DITHER_STRENGTH", "Dithering strength", 0.0, 1.0),
            ("VK_BASALT_LUMINANCE_STRENGTH", "Luminance strength", 0.0, 1.0),
            ("VK_BASALT_COLOR_STRENGTH", "Color strength", 0.0, 1.0),
            ("VK_BASALT_BLOOM_STRENGTH", "Bloom strength", 0.0, 1.0),
            ("VK_BASALT_SSAO_STRENGTH", "SSAO strength", 0.0, 1.0),
            ("VK_BASALT_VIGNETTE_STRENGTH", "Vignette strength", 0.0, 1.0),
            ("VK_BASALT_CHROMATIC_ABER_STRENGTH", "Chromatic aberration strength", 0.0, 1.0),
            ("VK_BASALT_MOTION_BLUR_STRENGTH", "Motion blur strength", 0.0, 1.0),
            ("VK_BASALT_SHARPEN_RADIUS", "Sharpening radius", 0.0, 10.0),
            ("VK_BASALT_FXAA_RADIUS", "FXAA radius", 0.0, 10.0),
            ("VK_BASALT_SMAA_RADIUS", "SMAA radius", 0.0, 10.0),
            ("VK_BASALT_LUT_RADIUS", "LUT radius", 0.0, 10.0),
            ("VK_BASALT_TONEMAP_RADIUS", "Tonemapping radius", 0.0, 10.0),
            ("VK_BASALT_HDR_RADIUS", "HDR radius", 0.0, 10.0),
            ("VK_BASALT_DITHER_RADIUS", "Dithering radius", 0.0, 10.0),
            ("VK_BASALT_LUMINANCE_RADIUS", "Luminance radius", 0.0, 10.0),
            ("VK_BASALT_COLOR_RADIUS", "Color radius", 0.0, 10.0),
            ("VK_BASALT_BLOOM_RADIUS", "Bloom radius", 0.0, 10.0),
            ("VK_BASALT_SSAO_RADIUS", "SSAO radius", 0.0, 10.0),
            ("VK_BASALT_VIGNETTE_RADIUS", "Vignette radius", 0.0, 10.0),
            ("VK_BASALT_CHROMATIC_ABER_RADIUS", "Chromatic aberration radius", 0.0, 10.0),
            ("VK_BASALT_MOTION_BLUR_RADIUS", "Motion blur radius", 0.0, 10.0),
        ],
        "software_requirement": "vkbasalt",
    },
    "GameMode": {
        "enable_label": "Enable GameMode",
        "enable_tooltip": "Enable GameMode optimization",
        "command_prefix": "gamemoderun",
        "toggles": [
            ("GAME_MODE", "Enable GameMode optimization"),
        ],
        "inputs": [],
        "software_requirement": "gamemoded",
    },
    "Gamescope": {
        "enable_label": "Enable Gamescope",
        "enable_tooltip": "Enable Gamescope",
        "command_prefix": "gamescope",
        "command_suffix": "--",
        "toggles": [
            ("-f", "Force full screen mode"),
            ("-b", "Enable borderless window mode"),
            ("-n", "Disable the gamescope compositor"),
            ("-c", "Enable VSync"),
            ("-q", "Enable quiet mode"),
        ],
        "inputs": [
            ("-W", "Set window width", "e.g., 1920"),
            ("-H", "Set window height", "e.g., 1080"),
            ("-r", "Set refresh rate", "e.g., 60"),
            ("-w", "Set game width", "e.g., 1920"),
            ("-h", "Set game height", "e.g., 1080"),
            ("-d", "Specify display", "e.g., :0"),
            ("-p", "Specify port", "e.g., 8080"),
            ("-x", "Set X offset", "e.g., 10"),
            ("-y", "Set Y offset", "e.g., 10"),
            ("--prefer-vk-device", "Prefer specific Vulkan device", "e.g., 0"),
            ("--steam", "Enable Steam integration features", ""),
        ],
        "dropdowns": {},
        "software_requirement": "gamescope",
    },
    "DXVK": {
        "enable_label": "Enable DXVK",
        "enable_tooltip": "Enable DXVK translation",
        "env_prefix": "",
        "toggles": [
            ("DXVK_HUD", "Enable DXVK HUD"),
            ("DXVK_ASYNC", "Enable asynchronous shader compilation"),
            ("DXVK_ENABLE_SHADER_CACHE", "Enable shader cache"),
            ("DXVK_SHADER_LOG", "Enable shader logging"),
            ("DXVK_DEBUG_SHADERS", "Enable shader debugging"),
            ("DXVK_ENABLE_SHADER_DEBUG_INFO", "Enable shader debug information"),
            ("DXVK_USE_D3D11_SWITCHABLE_GFX", "Enable D3D11 switchable graphics"),
            ("DXVK_USE_LINEAR_ALLOCATION", "Enable linear allocation"),
            ("DXVK_USE_STAGING_BUFFERS", "Enable staging buffers"),
            ("DXVK_USE_NONBLOCKING_THREADS", "Enable non-blocking threads"),
            ("DXVK_USE_ASYNC_PRESENT", "Enable asynchronous presentation"),
            ("DXVK_USE_SHADER_GFX9", "Enable shader compilation for GFX9"),
            ("DXVK_USE_SHADER_GFX10", "Enable shader compilation for GFX10"),
            ("DXVK_USE_SHADER_GFX10_3", "Enable shader compilation for GFX10.3"),
            ("DXVK_USE_SHADER_GFX11", "Enable shader compilation for GFX11"),
            ("DXVK_ENABLE_SHADER_OPTIMIZATIONS", "Enable shader optimizations"),
            ("DXVK_ENABLE_SHADER_PRECOMPILATION", "Enable shader precompilation"),
            ("DXVK_ENABLE_SHADER_PRECACHE", "Enable shader precache"),
            ("DXVK_ENABLE_SHADER_PRELOAD", "Enable shader preload"),
            ("DXVK_ENABLE_SHADER_PREWARM", "Enable shader prewarm"),
            ("DXVK_ENABLE_SHADER_PREOPTIMIZE", "Enable shader preoptimize"),
            ("DXVK_ENABLE_SHADER_PRECOMPILEALL", "Enable shader precompile for all"),
            ("DXVK_ENABLE_SHADER_PRECACHEALL", "Enable shader precache for all"),
            ("DXVK_ENABLE_SHADER_PRELOADALL", "Enable shader preload for all"),
            ("DXVK_ENABLE_SHADER_PREWARMALL", "Enable shader prewarm for all"),
            ("DXVK_ENABLE_SHADER_PREOPTIMIZEALL", "Enable shader preoptimize for all"),
        ],
        "inputs": [
            ("DXVK_HUD", "Specify HUD info", "e.g., fps,version"),
            ("DXVK_STATE_CACHE_PATH", "Path to state cache", "e.g., /path/to/cache"),
            ("DXVK_SHADER_CACHE_PATH", "Path to shader cache", "e.g., /path/to/cache"),
            ("DXVK_LOG_LEVEL", "Set log level", "e.g., info"),
            ("DXVK_MAX_FRAME_LATENCY", "Set max frame latency", "e.g., 2"),
            ("DXVK_MAX_FRAMES_IN_FLIGHT", "Set max frames in flight", "e.g., 3"),
            ("DXVK_FORCE_FEATURE_LEVEL", "Force feature level", "e.g., 11_0"),
            ("DXVK_SHADER_MODEL", "Specify shader model", "e.g., 5"),
            ("DXVK_MAX_SHADER_RESOURCE_GROUPS", "Set max shader resource groups", "e.g., 16"),
        ],
        "software_requirement": "dxvk",
    },
    "ProtonCustom": {
        "enable_label": "Enable ProtonCustom",
        "enable_tooltip": "Enable custom Proton settings",
        "env_prefix": "",
        "toggles": [
            ("PROTON_USE_WINED3D", "Force use of WineD3D"),
            ("PROTON_NO_ESYNC", "Disable explicit synchronization"),
            ("PROTON_NO_FSYNC", "Disable frame synchronization"),
            ("PROTON_USE_SECCOMP", "Enable seccomp sandboxing"),
            ("PROTON_USE_WINETRICKS", "Enable use of Winetricks"),
            ("PROTON_LOG", "Enable Proton logging"),
            ("PROTON_DISABLE_D3D11", "Disable Direct3D 11 support"),
            ("PROTON_DISABLE_D3D10", "Disable Direct3D 10 support"),
            ("PROTON_USE_WINED3D11", "Force WineD3D for D3D11"),
            ("PROTON_USE_WINED3D10", "Force WineD3D for D3D10"),
            ("PROTON_USE_WINED3D9", "Force WineD3D for D3D9"),
            ("PROTON_USE_D3D9EX", "Enable Direct3D 9Ex support"),
            ("PROTON_USE_D3D10LAYER", "Enable Direct3D 10 layer"),
            ("PROTON_USE_D3D11LAYER", "Enable Direct3D 11 layer"),
            ("PROTON_USE_D3D10MULTITHREADING", "Enable D3D10 multithreading"),
            ("PROTON_USE_D3D11MULTITHREADING", "Enable D3D11 multithreading"),
            ("PROTON_USE_VULKAN", "Force use of Vulkan"),
            ("PROTON_USE_OPENGL", "Force use of OpenGL"),
            ("PROTON_ENABLE_NVAPI", "Enable NVAPI support"),
            ("PROTON_DISABLE_NVAPI", "Disable NVAPI support"),
            ("PROTON_USE_STAGING", "Use staging branch of Wine"),
            ("PROTON_USE_PULSEAUDIO", "Force use of PulseAudio"),
            ("PROTON_USE_PIPEWIRE", "Force use of PipeWire"),
            ("PROTON_USE_ALSA", "Force use of ALSA"),
            ("PROTON_USE_JACK", "Force use of JACK"),
            ("PROTON_USE_XAUDIO2", "Force use of XAudio2"),
            ("PROTON_USE_FMOD", "Force use of FMOD"),
            ("PROTON_USE_DSOUND", "Force use of DirectSound"),
            ("PROTON_USE_WASAPI", "Force use of WASAPI"),
            ("PROTON_USE_DSOUND_HRTF", "Enable HRTF in DirectSound"),
            ("PROTON_USE_DSOUND_EFX", "Enable EFX in DirectSound"),
            ("PROTON_USE_DSOUND_REVERB", "Enable reverb in DirectSound"),
            ("PROTON_USE_DSOUND_3D", "Enable 3D audio in DirectSound"),
            ("PROTON_USE_DSOUND_EAX", "Enable EAX in DirectSound"),
            ("PROTON_USE_DSOUND_ALC", "Enable ALC in DirectSound"),
            ("PROTON_USE_DSOUND_ALC_HRTF", "Enable HRTF in DirectSound ALC"),
            ("PROTON_USE_DSOUND_ALC_EFX", "Enable EFX in DirectSound ALC"),
            ("PROTON_USE_DSOUND_ALC_REVERB", "Enable reverb in DirectSound ALC"),
            ("PROTON_USE_DSOUND_ALC_3D", "Enable 3D audio in DirectSound ALC"),
            ("PROTON_USE_DSOUND_ALC_EAX", "Enable EAX in DirectSound ALC"),
            ("PROTON_FORCE_VKLAYER_ENABLES", "Force Vulkan layer enables"),
            ("PROTON_WAIT_FOR_PLAY", "Wait for steam 'Play' press"),
        ],
        "inputs": [
            ("PROTON_LOG_DIR", "Path to log directory", "e.g., /path/to/log"),
            ("PROTON_DUMP_DEBUG_COMMANDS", "Path to dump debug commands", "e.g., /tmp/proton_debug"),
            ("PROTON_WINE_DEBUG", "Set Wine debug level (e.g., +steam)", "e.g., +steam,+rpc"),
        ],
    },
    "MesaOverlay": {
        "enable_label": "Enable MesaOverlay",
        "enable_tooltip": "Enable Mesa overlay",
        "env_prefix": "",
        "toggles": [
            ("MESA_OVERLAY", "Enable Mesa overlay"),
            ("MESA_OVERLAY_FPS", "Display FPS in Mesa overlay"),
            ("MESA_OVERLAY_GPU", "Display GPU usage in Mesa overlay"),
            ("MESA_OVERLAY_CPU", "Display CPU usage in Mesa overlay"),
            ("MESA_OVERLAY_MEMORY", "Display memory usage in Mesa overlay"),
            ("MESA_OVERLAY_TEMP", "Display GPU temperature in Mesa overlay"),
            ("MESA_OVERLAY_POWER", "Display GPU power usage in Mesa overlay"),
            ("MESA_OVERLAY_LOG", "Enable logging for Mesa overlay"),
            ("MESA_OVERLAY_SHORT", "Display a shorter overlay in Mesa"),
            ("MESA_OVERLAY_FULL", "Display a full overlay in Mesa"),
            ("MESA_OVERLAY_NOBACKGROUND", "Disable overlay background"),
            ("MESA_OVERLAY_TRANSPARENT", "Make overlay transparent"),
        ],
        "inputs": [
            ("MESA_OVERLAY_CONFIG", "Path to custom Mesa overlay config file", "e.g., /path/to/config"),
            ("MESA_OVERLAY_XOFFSET", "Adjust X offset of overlay", "e.g., 10"),
            ("MESA_OVERLAY_YOFFSET", "Adjust Y offset of overlay", "e.g., 10"),
            ("MESA_OVERLAY_COLOR", "Set overlay color", "e.g., #FF0000"),
            ("MESA_OVERLAY_FONT_SIZE", "Set font size", "e.g., 12"),
            ("MESA_OVERLAY_LOG_FILE", "Path to log file", "e.g., /path/to/log"),
            ("MESA_OVERLAY_TRANSPARENCY", "Set transparency level", "e.g., 0.5"),
        ],
        "dropdowns": {
            "MESA_OVERLAY_ALIGN": {
                "label": "ALIGN:",
                "options": ["top", "bottom", "left", "right"],
                "tooltip": "Align the Mesa overlay",
                "default": "top",
            }
        },
    },
} 